active_nnm_url: http://online.wsj.com/mdc/public/page/2_3021-activnnm-actives.html
active_nyse_url: http://online.wsj.com/mdc/public/page/2_3021-activnyse-actives.html
search_url: http://d.yimg.com/autoc.finance.yahoo.com/autoc?
