development:
  adapter: postgresql
  database: my_winning_trade_development
  user: platform45
  host: localhost

test:
  adapter: postgresql
  database: my_winning_trade_test
  user: platform45
  host: localhost
  template: template0

